config/routes.rb
Rails.application.routes.draw do
  #get 'dashboard/index'
  get 'dashboard', to: 'dashboard#index', as: :dashboard
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout' }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  resources :notes
  resources :dashboard
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  content    :text
#  note_name  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_notes_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class Note < ApplicationRecord
  belongs_to :user

  validates :note_name, presence: true
  validates :content, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  username               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_forgery_protection
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation])
  end

  def after_sign_in_path_for(resource)
    dashboard_path
  end

  def after_sign_up_path_for(resource)
    dashboard_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:index, :show, :edit, :update, :destroy]

  def index
    @username = current_user&.username

    # Check if current_user is not nil before accessing notes
  end

  private
  def set_note
    @notes = current_user.notes
  end

  def note_params
    params.require(:note).permit(:note_name, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  def index
    @notes = current_user.notes
  end

  def show
    # Note: The set_note before_action already retrieves the note
  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note, notice: 'Note was successfully created.'
    else
      render :new
    end
  end

  def edit
    # Note: The set_note before_action already retrieves the note
  end

  def update
    if @note.update(note_params)
      redirect_to dashboard_path, notice: 'Note was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_url, notice: 'Note was successfully destroyed.'
  end

  private

  def set_note
    @note = current_user.notes.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:note_name, :content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    # Your index action code here
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h1 class="welcome">Welcome <%= @username %></h1>
<h2>My notes</h2>
<div class="btn-container">
  <%= link_to new_note_path, class: "btn btn-outline-dark" do %>
    Add a new note
  <% end %>
</div>
<% @notes.each do |note| %>
  <div class="card rounded border-0 bg-dark p-2 text-white" style="width: 18rem;">
    <div class="card-body link-dark">
      <h4><%= link_to note.note_name, note, class: "text-white" %></h4>
      <%# Render the partial only when the note is clicked %>
      <% if params[:id] == note.id.to_s %>
        <%= render partial: 'notes/show', locals: { note: note } %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="center-container">
  <%= image_tag('brain-juice.gif', alt: 'brain gif', class: 'custom-image') %>
</div>

<div class="cntr-container">
  <%= image_tag('brain-flow.gif', alt: 'brain juice lettering', class: 'cstm-image') %>
</div>

<div class="btn-container">
  <%= link_to new_user_session_path do %>
    <button type="button" class="btn btn-outline-dark">Sign in</button>
  <% end %>

  <%= link_to new_user_registration_path do %>
    <button type="button" class="btn btn-outline-dark">Sign up</button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> 🧠 Brain Juice 🧃 </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gaegu:wght@300;400;700&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Bungee+Shade&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=BioRhyme:wght@300;400&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css2?family=Bungee+Shade&family=Chango&family=Comfortaa:wght@300;400;500&family=Monoton&display=swap" rel="stylesheet">

   <link href="https://fonts.googleapis.com/css2?family=Lilita+One&display=swap" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

  </head>

  <body>
    <% if user_signed_in? %> 
      <%= render "share/navbar" %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>
    

  </body>
</html>

app/views/notes/_form.html.erb
<!-- app/views/notes/_form.html.erb -->

<div class="card border-0 bg-light p-2 text-dark bg-opacity-75" style="min-width: 10rem; max-width: 30rem">
  <div class="card-body">
    <%= simple_form_for(@note) do |f| %>
      <%= f.error_notification %>
      <br>
      <div class="form-inputs">
        <%= f.input :note_name %>
        <br>
        <%= f.input :content %>
      </div>
      <br>

      <div class="btn-container">
        <div class="form-actions">
          <%= f.button :submit, "Submit", class: "btn btn-outline-dark" %>
        </div>
        <%= link_to dashboard_path, class: "btn btn-outline-dark ml-2" do %>
          Back
        <% end %>
      </div>

    <% end %>
  </div>  
</div>

app/views/notes/_show.html.erb
<!-- app/views/notes/show.html.erb -->

<h3><%= note.note_name %></h3>

<p><%= note.content %></p>

<%= link_to 'Edit', edit_note_path(note) %>

app/views/notes/edit.html.erb
<!-- app/views/notes/edit.html.erb -->

<h1>Edit Note</h1>

<%= render 'form' %>

app/views/notes/index.html.erb
<!-- app/views/notes/index.html.erb -->

<h1>Your Notes</h1>

<% @notes.each do |note| %>
  <h2><%= link_to note.note_name, note %></h2>
  <p><%= note.content %></p>
  <p><%= link_to 'Edit', edit_note_path(note) %></p>
  <p><%= link_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<!-- app/views/notes/new.html.erb -->

<h1>New Note</h1>

<%= render 'form' %>

app/views/notes/show.html.erb
<div class="card border-0 bg-light p-2 text-dark bg-opacity-75" style="min-width: 18rem;">
   <div class="card-header">Created on <%= @note.created_at.strftime("%A, %b %d %Y") %></div>
  <div class="card-body">
    <h1 class="card-title"><%= @note.note_name %></h1>
    <p class="card-text"><%= @note.content %></p>
  </div>

  <div class="btn-container">
    <%= link_to edit_note_path(@note), class: "btn btn-outline-dark" do %>
      Edit
    <% end %>

    <%= link_to dashboard_path, class: "btn btn-outline-dark" do %>
      Back
    <% end %>
  </div>

  <div class="card-footer">
    <small class="text-muted">Last updated <%= time_ago_in_words(@note.updated_at) %> ago</small>
  </div>
</div>

app/views/share/_navbar.html.erb
<nav class="navbar navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand font-size-lg" href="/dashboard">
      <%= image_tag('brain-flow.gif', alt: 'brain juice lettering', class: 'custm-image') %>
      <span class="logo-text">Brain Juice</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/dashboard">Clipboard</a> 
          </li>
          <li class="nav-item">
            <%= link_to 'New Note', new_note_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
          </li>
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link", data: { confirm: "Are you sure you want to sign out?" } %>
              </li>
            <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>